export const EXPERIENCE_LIST = [
  {
    role: "Front-End Developer | SNSoft Technology Inc.",
    period: "June 2025 – Oct 2025 | Onsite · Philippines ",
    details: [
      "Maintained and developed interactive H5, web, and landing pages using React.js, TypeScript, HTML, CSS and Tailwind CSS.",
      "Translated Figma designs into responsive, accessible, and cross-browser compatible UI components.",
      "Integrated REST APIs and real-time WebSocket communication using gRPC.",
      "Assisted in resolving issues from the bug list in a React Native project.",
      "Applied MVVM architecture principles for structured and maintainable front-end development.",
      "Contributed to a monorepo environment and collaborated with the Malaysia-based team using Git fork and upstream workflows to ensure consistent and aligned codebase management.",
    ],
    skills: [
      "React.js",
      "React Native",
      "TypeScript",
      "JavaScript",
      "Tailwind CSS",
      "HTML",
      "CSS",
      "Redux",
      "REST API",
      "Websocket",
      "gRPC",
      "Github",
      "Jira",
      "Lark",
    ],
  },
  {
    role: "Front-End Developer | Awesomelab Inc.",
    period: "July 2021 – March 2025 | Remote· Philippines ",
    details: [
      "Developed and maintained web applications for hotel management, CMS, HR, and data collection using Next.js, React.js, HTML, CSS, TypeScript, and Mantine UI.",
      "Translated Figma designs into responsive, accessible, and cross-browser compatible UI components.",
      "Integrated and consumed RESTful and GraphQL APIs to manage data flow.",
      "Collaborated on CI/CD and deployment workflows using Bitbucket and AWS CloudFront.",
      "Enhanced UI performance and maintainability by refactoring legacy code, optimizing data fetching with TanStack Query, reducing re-renders, and implementing Playwright for end-to-end testing. ",
      "Applied component-based, feature-based, and custom hook architecture patterns to ensure scalability, reusability, and clean code structure across projects. ",
    ],
    skills: [
      "Next.js",
      "React.js",
      "TypeScript",
      "JavaScript",
      "Mantine UI",
      "HTML",
      "CSS",
      "Zustand",
      "Jotai",
      "Nuqs",
      "REST API",
      "GraphQL",
      "GraphQL Subscriptions",
      "Amplify API (GraphQL)",
      "Apollo GraphQL",
      "Tanstack Query",
      "AWS Cognito Auth",
      "Playwright",
      "Git",
      "Bitbucket",
      "Jira",
    ],
  },
  {
    role: "Junior Programmer | HRD Singapore Pte. Ltd.",
    period: "June 2018 – June 2021 | Onsite · Philippines",
    details: [
      "Developed and maintained an internal system for house planners, streamlining operations across inventory, automation, and data extraction. ",
      "Migrated a legacy Magic XPA desktop app into a Vue.js-based web application using Ant Design, Node.js, Express.js, REST APIs, and MySQL",
    ],
    skills: [
      "Magic XPA",
      "HTML",
      "CSS",
      "JavaScript",
      "Vue.js",
      "Ant Design",
      "Node.js",
      "Express.js",
      "MySQL",
      "REST API",
      "Git",
    ],
  },
];
